// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppinglistApp.Data;

namespace ShoppinglistApp.Migrations.ShoppingList
{
    [DbContext(typeof(ShoppingListContext))]
    partial class ShoppingListContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShoppinglistApp.Models.ShoppingListItem", b =>
                {
                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ShoppinglistListID")
                        .HasColumnType("int");

                    b.HasKey("ItemName");

                    b.HasIndex("ShoppinglistListID");

                    b.ToTable("ShoppingListItem");
                });

            modelBuilder.Entity("ShoppinglistApp.Models.Shoppinglist", b =>
                {
                    b.Property<int>("ListID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ListName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ListID");

                    b.ToTable("Shoppinglist");
                });

            modelBuilder.Entity("ShoppinglistApp.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ShoppinglistUser", b =>
                {
                    b.Property<int>("AllowedUsersID")
                        .HasColumnType("int");

                    b.Property<int>("ShoppinglistsListID")
                        .HasColumnType("int");

                    b.HasKey("AllowedUsersID", "ShoppinglistsListID");

                    b.HasIndex("ShoppinglistsListID");

                    b.ToTable("ShoppinglistUser");
                });

            modelBuilder.Entity("ShoppinglistApp.Models.ShoppingListItem", b =>
                {
                    b.HasOne("ShoppinglistApp.Models.Shoppinglist", null)
                        .WithMany("Items")
                        .HasForeignKey("ShoppinglistListID");
                });

            modelBuilder.Entity("ShoppinglistUser", b =>
                {
                    b.HasOne("ShoppinglistApp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("AllowedUsersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShoppinglistApp.Models.Shoppinglist", null)
                        .WithMany()
                        .HasForeignKey("ShoppinglistsListID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShoppinglistApp.Models.Shoppinglist", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
